# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-15 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_courseperformance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseperformance',
            name='id',
        ),
        migrations.AlterField(
            model_name='courseperformance',
            name='quiz_attempted',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
