# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-22 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_auto_20170615_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='question1',
            name='alternate_question_description',
            field=models.FileField(default=1, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question1',
            name='alternate_question_hint1',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question1',
            name='alternate_question_option1',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question1',
            name='alternate_question_option2',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question1',
            name='alternate_question_option3',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question1',
            name='alternate_question_option4',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question1',
            name='alternate_question_right_answer',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question1',
            name='alternate_question_title',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
