# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-22 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_quiz_performance_noofquestionsattempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_performance',
            name='numOfQuestions',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
