# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-24 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_auto_20170624_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_performance',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quiz_performance',
            name='quiz_no',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
