# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-26 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0010_auto_20170626_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePerformanceHistory',
            fields=[
                ('quiz_attempted', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('quiz_question_wrong', models.CharField(max_length=250)),
                ('quiz_question_hintTaken', models.CharField(max_length=250)),
                ('quiz_question_wrongNo', models.CharField(max_length=250)),
                ('quiz_hintNo', models.CharField(max_length=250)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.Course')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
