# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-12 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_quizperformancehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions_alternate_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions_alternate_string',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
